// ============================================================
//  OCRtoODT — Dialog: OCR Completion
//  File: dialogs/OcrCompletionDialog.h
//
//  Responsibility:
//      Modal dialog displayed after OCR processing completes.
//
//      This dialog:
//          - Notifies the user that text recognition has finished
//          - Explains how to begin editing recognized text
//          - Displays a theme-aware demo illustration
//          - Optionally plays a completion sound (config-driven)
//
//  Architecture rules:
//      - NO OCR logic
//      - NO pipeline interaction
//      - NO configuration writes
//      - NO business logic
//      - Reads settings only via ConfigManager
//      - Uses ThemeManager only to resolve current theme
//
//  UX role:
//      This dialog is the reference notification pattern
//      for future UI completion events in OCRtoODT.
//
// ============================================================

#ifndef OCR_COMPLETION_DIALOG_H
#define OCR_COMPLETION_DIALOG_H

#include <QDialog>
#include <QSoundEffect>

// Forward declaration generated by uic
namespace Ui {
class OcrCompletionDialog;
}

class OcrCompletionDialog : public QDialog
{
    Q_OBJECT

public:
    explicit OcrCompletionDialog(QWidget *parent = nullptr);
    ~OcrCompletionDialog() override;

private:
    // --------------------------------------------------------
    // UI helpers
    // --------------------------------------------------------

    // Selects demo SVG illustration according to current theme
    void applyThemeSpecificIllustration();

    // Initializes and plays completion sound if enabled in config
    void initCompletionSound();

private:
    Ui::OcrCompletionDialog *ui = nullptr;

    // Sound effect must persist while dialog is alive
    QSoundEffect *m_soundEffect = nullptr;
};

#endif // OCR_COMPLETION_DIALOG_H
